/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root.tsx'
import { Route as LayoutImport } from './routes/_layout.tsx'
import { Route as LayoutIndexImport } from './routes/_layout/index.tsx'
import { Route as LayoutRentMinerImport } from './routes/_layout/rent-miner.tsx'
import { Route as LayoutInviteImport } from './routes/_layout/invite.tsx'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRentMinerRoute = LayoutRentMinerImport.update({
  path: '/rent-miner',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInviteRoute = LayoutInviteImport.update({
  path: '/invite',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/invite': {
      id: '/_layout/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof LayoutInviteImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/rent-miner': {
      id: '/_layout/rent-miner'
      path: '/rent-miner'
      fullPath: '/rent-miner'
      preLoaderRoute: typeof LayoutRentMinerImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutInviteRoute,
    LayoutRentMinerRoute,
    LayoutIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/invite",
        "/_layout/rent-miner",
        "/_layout/"
      ]
    },
    "/_layout/invite": {
      "filePath": "_layout/invite.tsx",
      "parent": "/_layout"
    },
    "/_layout/rent-miner": {
      "filePath": "_layout/rent-miner.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
